### ISSUE TITLE
Failed to download Cloudflared executable.

### ISSUE THREAD

**Issue by TRoydaws** [PawanOsman/ChatGPT#100]
Failed to download Cloudflared executable.
💡 Server is running at http://localhost:3040

🔗 Local Base URL: http://localhost:3040/v1
🔗 Local Endpoint: http://localhost:3040/v1/chat/completions

🔗 Public Endpoint: (Failed to start cloudflared tunnel, please restart the server.)
📝 Author: Pawan.Krd
🌐 Discord server: https://discord.gg/pawan
🌍 GitHub Repository: https://github.com/PawanOsman/ChatGPT
💖 Don't forget to star the repository if you like this project!
                                                     System: Successfully refreshed session ID and token. (Now it's ready to process requests)
System: Successfully refreshed session ID and token.
System: Successfully refreshed session ID and token.
System: Successfully refreshed session ID and token.
System: Successfully refreshed session ID and token.
System: Successfully refreshed session ID and token.
System: Successfully refreshed session ID and token.

**Comment by jeffery9** [comment]
#96

**Comment by PawanOsman** [comment]
@TRoydaws it happens when you run it on Android, I will try to fix the Cloudflared tunnel for Termux too.
