### ISSUE TITLE
Error message from OpenAI: Our systems have detected unusual activity from your device. Please try again later.

### ISSUE THREAD

**Issue by AndyLin2020** [PawanOsman/ChatGPT#101]
Starting the application...
> chatgpt@1.0.0 start
> tsc && node dist/app.js
💡 Server is running at http://localhost:3040
🔗 Local Base URL: http://localhost:3040/v1
🔗 Local Endpoint: http://localhost:3040/v1/chat/completions
🔗 Public Base URL: https://county-locale-cz-successful.trycloudflare.com/v1
🔗 Public Endpoint: https://county-locale-cz-successful.trycloudflare.com/v1/chat/completions
📝 Author: Pawan.Krd
🌐 Discord server: https://discord.gg/pawan
🌍 GitHub Repository: https://github.com/PawanOsman/ChatGPT
💖 Don't forget to star the repository if you like this project!
System: Successfully refreshed session ID and token. (Now it's ready to process requests)
Request: POST /v1/chat/completions 8 messages (stream-enabled)
Request: POST /v1/chat/completions 8 messages (stream-enabled)
Request: POST /v1/chat/completions 8 messages (stream-enabled)
System: Successfully refreshed session ID and token. 
System: Successfully refreshed session ID and token. 
Error refreshing session ID, retrying in 2 minute...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN.
System: Successfully refreshed session ID and token. 
System: Successfully refreshed session ID and token.

**Comment by 2013224691** [comment]
I got the same problem, any solution? 🙏🏻

**Comment by hubaolong3632** [comment]
![image](https://github.com/skzhengkai/free-chatgpt-api/assets/87271391/c300458e-bbaf-444d-8823-07489a18beb4)
{
    "message": null,
    "conversation_id": "69a12542-6816-405d-8bb8-13b08535f105",
    "error": "Our systems have detected unusual activity from your device. Please try again later."
}
使用对应教程已经挂了，现在使用此教程出现这个问题有没有解决方法，有什么方法解决吗

**Comment by PawanOsman** [comment]
Fixed, please update.
