### ISSUE TITLE
Our systems have detected unusual activity from your device. Please try again later

### ISSUE THREAD

**Issue by hubaolong3632** [PawanOsman/ChatGPT#103]
![image](https://github.com/skzhengkai/free-chatgpt-api/assets/87271391/c300458e-bbaf-444d-8823-07489a18beb4)
{
    "message": null,
    "conversation_id": "69a12542-6816-405d-8bb8-13b08535f105",
    "error": "Our systems have detected unusual activity from your device. Please try again later."
}
使用对应教程已经挂了，现在使用此教程出现这个问题有没有解决方法，有什么方法解决吗

**Comment by hubaolong3632** [comment]
Is there a solution

**Comment by hubaolong3632** [comment]
It came out today

**Comment by hubaolong3632** [comment]
I see that the interface on the official website has newly added whether this detection is illegal. How to break it
https://ab.chatgpt.com/v1/rgstr

**Comment by hubaolong3632** [comment]
https://chat.openai.com/ces/v1/t 
![image](https://github.com/PawanOsman/ChatGPT/assets/87271391/282fb73b-bd8f-4953-8808-81b0f403c567)

**Comment by 2013224691** [comment]
I got the same problem. Does anyone know any solution?

**Comment by buhe** [comment]
Same issue #101

**Comment by RexZheng-cug** [comment]
same as #101 , did anyone have solved this yet?

**Comment by PawanOsman** [comment]
Duplicate Issue #101
