### ISSUE TITLE
invalid_request_error

### ISSUE THREAD

**Issue by TinkuMajhi** [PawanOsman/ChatGPT#107]
invalid_request_error

MSG : Error getting a new session, please try again later, if the issue persists, please open an issue on the GitHub repository, https://github.com/PawanOsman/ChatGPT

**Comment by SleepInfinity** [comment]
I have the exact same issue.
![-2147483648_-215120](https://github.com/PawanOsman/ChatGPT/assets/161524919/fbb59539-ed44-4169-996a-e6c93537522a)

**Comment by PawanOsman** [comment]
Please make sure to use a U.S. VPN,
you can't host it on cloud because your IP will be blocked by OpenAI,

you have to use a U.S. VPN or residential proxy

**Comment by SleepInfinity** [comment]
> Please make sure to use a U.S. VPN, you can't host it on cloud because your IP will be blocked by OpenAI,
> 
> you have to use a U.S. VPN or residential proxy

I tried using US rotating proxy but the same error persist.

**Comment by SleepInfinity** [comment]
Is there any way to make sure that the api is using that proxy?

**Comment by PawanOsman** [comment]
@SleepInfinity, make sure to set both `PROXY` and `PROXY_AUTH` to true. Also, ensure that you set the `PROXY_HOST` and `PROXY_PORT` correctly. Additionally, make sure to specify the correct proxy protocol.

You can also try to write the username and password between double quotes

**Comment by SleepInfinity** [comment]
> @SleepInfinity, make sure to set both `PROXY` and `PROXY_AUTH` to true. Also, ensure that you set the `PROXY_HOST` and `PROXY_PORT` correctly. Additionally, make sure to specify the correct proxy protocol.
> 
> You can also try to write the username and password between double quotes

![IMG_20240422_161554_656](https://github.com/PawanOsman/ChatGPT/assets/161524919/4f222d09-7633-4048-b660-391ba2316bfa)
I tried both with and without double quotes but still same error and also Im sure that the protocol is http as mentioned in the proxyscrape dashboard and also I tried the proxy with a simple python code and it works fine.

**Comment by notV3NOM** [comment]
Im just getting empty responses now. Was working flawlessly until yesterday

**Comment by SleepInfinity** [comment]
> Im just getting empty responses now. Was working flawlessly until yesterday

What you did to make it work?

**Comment by notV3NOM** [comment]
> What you did to make it work?

I did not have the issue you are facing

**Comment by SleepInfinity** [comment]
> > @SleepInfinity, make sure to set both `PROXY` and `PROXY_AUTH` to true. Also, ensure that you set the `PROXY_HOST` and `PROXY_PORT` correctly. Additionally, make sure to specify the correct proxy protocol.
> > You can also try to write the username and password between double quotes
> 
> ![IMG_20240422_161554_656](https://private-user-images.githubusercontent.com/161524919/324493980-4f222d09-7633-4048-b660-391ba2316bfa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTg5MjIsIm5iZiI6MTcxMzg1ODYyMiwicGF0aCI6Ii8xNjE1MjQ5MTkvMzI0NDkzOTgwLTRmMjIyZDA5LTc2MzMtNDA0OC1iNjYwLTM5MWJhMjMxNmJmYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwNzUwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTc2ZmU4ZmFkNzRjNGZmOTlhYjBlNjRjYTIwMjA4ZGU4ZGM0ZGU3NjA4ZGI5NTAxZjNiMGI4YzRhMjEwYjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PwY__Qvx_sq6e1JTlloG0mMCpGy6kTNuBCZS1OOFJzs) I tried both with and without double quotes but still same error and also Im sure that the protocol is http as mentioned in the proxyscrape dashboard and also I tried the proxy with a simple python code and it works fine.

My problem is now solved the app wasn't detecting and using the proxy inside the .env file but now with python everything is working properly and I think ill make the same app in python and share it is it possible?

**Comment by PawanOsman** [comment]
@SleepInfinity, you must have done something incorrectly because the .env file is working fine, and the proxies are functioning properly with it.

Perhaps you have more knowledge about Python, that's why you couldn't set up this Node.js project.

**Comment by SleepInfinity** [comment]
> @SleepInfinity, you must have done something incorrectly because the .env file is working fine, and the proxies are functioning properly with it.
> 
> Perhaps you have more knowledge about Python, that's why you couldn't set up this Node.js project.

Yes, anyways thankyou for your help 😄
