### ISSUE TITLE
pro

### ISSUE THREAD

**Issue by tomridder** [PawanOsman/ChatGPT#109]
i run the docker 

docker run -dp 3043:3043 pawanosman/chatgpt:latest

and try 

curl --location 'http://127.0.0.1:3043/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-antshu' \
--data '{
  	"model": "gpt-3.5-turbo",
  	"messages": [{"role": "user", "content": "hello"}],
 	"stream":false
}'

but it says 

curl: (56) Recv failure: Connection reset by pee

**Comment by PawanOsman** [comment]
@tomridder the server will run on port 3040, so if you want to change the port you have to change only the host port

use the default port
```bash
docker run -dp 3040:3040 pawanosman/chatgpt:latest
```

or only change the host port

```bash
docker run -dp 3043:3040 pawanosman/chatgpt:latest
```
