### ISSUE TITLE
The American VPN I used in https://web.chatboxai.app/ is normal to work normally, but there is a problem with your API sample code access. How can I solve it?

### ISSUE THREAD

**Issue by Lucas-CX** [PawanOsman/ChatGPT#110]
![image](https://github.com/PawanOsman/ChatGPT/assets/57147405/8354025a-0a57-4de1-965c-3591e9486203)

**Comment by PawanOsman** [comment]
I see an internal server error happened in the screenshot you provided, so it means there isn't any issue with the sample code I provides, make sure the server is running and working fine

**Comment by hubaolong3632** [comment]
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
@PawanOsman What should I do if this problem occurs, but I am using a US server with a US native address

**Comment by HePingLaoSan** [comment]
It worked before, but now I'm having the same problem

**Comment by Ilyshkadwaushka** [comment]
Same problem. How to fix?
