### ISSUE TITLE
error while getting data

### ISSUE THREAD

**Issue by sudityashrivastav** [PawanOsman/ChatGPT#111]
{
  "status": false,
  "error": {
    "message": "An error occurred. please try again. Additionally, ensure that your request complies with OpenAI's policy.",
    "type": "invalid_request_error"
  },
  "support": "https://discord.pawan.krd"
}

this is the error I a getting

**Comment by SleepInfinity** [comment]
Can you show us how are you making the request to the api?

**Comment by PawanOsman** [comment]
@sudityashrivastav Your request should not contain anything against OpenAI policy

**Comment by somenzz** [comment]
I'm running it on my LA server.

 curl http://127.0.0.1:3040/v1/chat/completions   -H "Content-Type: application/json"   -H "Authorization: Bearer any_string_you_like"   -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
    "stream": false
    }'
{"status":false,"error":{"message":"Error getting a new session, If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.","type":"invalid_request_error"},"support":"https://discord.pawan.krd"}

**Comment by lyh0825** [comment]
> I'm running it on my LA server.
> 
> curl http://127.0.0.1:3040/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer any_string_you_like" -d '{ "model": "gpt-3.5-turbo", "messages": [ { "role": "user", "content": "Hello!" } ], "stream": false }' {"status":false,"error":{"message":"Error getting a new session, If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.","type":"invalid_request_error"},"support":"[https://discord.pawan.krd"}](https://discord.pawan.krd%22%7D)

I had the same problem. Did you solve it

**Comment by SleepInfinity** [comment]
> I'm running it on my LA server.
> 
> curl http://127.0.0.1:3040/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer any_string_you_like" -d '{ "model": "gpt-3.5-turbo", "messages": [ { "role": "user", "content": "Hello!" } ], "stream": false }' {"status":false,"error":{"message":"Error getting a new session, If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.","type":"invalid_request_error"},"support":"[https://discord.pawan.krd"}](https://discord.pawan.krd%22%7D)

Your country may be blocked from accessing chat gpt without login.
Try go to chatgpt.com on a new browser
If you can't access it it means your country is blocked.

**Comment by PawanOsman** [comment]
@somenzz The project is still working. The only issue, I believe, is that your IP might be blocked by OpenAI, or you need to use a good IP address.
Note that you have a very small chance of success using VPS, shared hosting, or shared IPs. You must use a residential IP to be able to access it.

**Comment by Ezi1h** [comment]
@PawanOsman Hi, I also deployed it to the vps in Los Angeles, but it was unstable, and I always encountered this error frequently. It must not be that the ip was banned, otherwise I would not receive a response. I directly connected the [xray proxy](https://github.com/XTLS/Xray-core) on this vps in my local Windows. And it can be used normally without logging in to `https://chat.openai.com/` in the browser, and the response speed is normal. I do not know how to solve this problem😢...

**Comment by SleepInfinity** [comment]
> @PawanOsman Hi, I also deployed it to the vps in Los Angeles, but it was unstable, and I always encountered this error frequently. It must not be that the ip was banned, otherwise I would not receive a response. I directly connected the [xray proxy](https://github.com/XTLS/Xray-core) on this vps in my local Windows. And it can be used normally without logging in to `https://chat.openai.com/` in the browser, and the response speed is normal. I do not know how to solve this problem😢...

Its possible that they are banning your server's ip temporary

**Comment by Ezi1h** [comment]
> > @PawanOsman Hi, I also deployed it to the vps in Los Angeles, but it was unstable, and I always encountered this error frequently. It must not be that the ip was banned, otherwise I would not receive a response. I directly connected the [xray proxy](https://github.com/XTLS/Xray-core) on this vps in my local Windows. And it can be used normally without logging in to `https://chat.openai.com/` in the browser, and the response speed is normal. I do not know how to solve this problem😢...
> 
> Its possible that they are banning your server's ip temporary

The banned timing seemed very short, I sent it a few times, then I got an error, sent it again normally, In ten attempts, there may be two to three errors...😂

**Comment by m00nfly** [comment]
> @PawanOsman Hi, I also deployed it to the vps in Los Angeles, but it was unstable, and I always encountered this error frequently. It must not be that the ip was banned, otherwise I would not receive a response. I directly connected the [xray proxy](https://github.com/XTLS/Xray-core) on this vps in my local Windows. And it can be used normally without logging in to `https://chat.openai.com/` in the browser, and the response speed is normal. I do not know how to solve this problem😢...

Using a VPS IP can easily trigger cloudflare's robot identification mechanism, so there is a high probability that your IP cannot pass the verification of real people and robots.

**Comment by Ezi1h** [comment]
> > @PawanOsman Hi, I also deployed it to the vps in Los Angeles, but it was unstable, and I always encountered this error frequently. It must not be that the ip was banned, otherwise I would not receive a response. I directly connected the [xray proxy](https://github.com/XTLS/Xray-core) on this vps in my local Windows. And it can be used normally without logging in to `https://chat.openai.com/` in the browser, and the response speed is normal. I do not know how to solve this problem😢...
> 
> Using a VPS IP can easily trigger cloudflare's robot identification mechanism, so there is a high probability that your IP cannot pass the verification of real people and robots.

But I have to use vps because openai is not allowed in my country... 😭

**Comment by SleepInfinity** [comment]
> > > @PawanOsman Hi, I also deployed it to the vps in Los Angeles, but it was unstable, and I always encountered this error frequently. It must not be that the ip was banned, otherwise I would not receive a response. I directly connected the [xray proxy](https://github.com/XTLS/Xray-core) on this vps in my local Windows. And it can be used normally without logging in to `https://chat.openai.com/` in the browser, and the response speed is normal. I do not know how to solve this problem😢...
> > 
> > 
> > Using a VPS IP can easily trigger cloudflare's robot identification mechanism, so there is a high probability that your IP cannot pass the verification of real people and robots.
> 
> But I have to use vps because openai is not allowed in my country... 😭

Me too but the best solution is to use a rotating residential us proxy.
I'm using the proxy from proxyscrape.com

**Comment by Kamarguera** [comment]
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
