### ISSUE TITLE
Error getting a new session, If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.

### ISSUE THREAD

**Issue by Marks-Jack** [PawanOsman/ChatGPT#113]
Error getting a new session, If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.

**Comment by PawanOsman** [comment]
@Marks-Jack  Please use a U.S. VPN. If you are already using one, OpenAI may blocked your IP/VPN IP, please use another VPN/IP.

**Comment by hubaolong3632** [comment]
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.

**Comment by hubaolong3632** [comment]
@PawanOsman Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.

**Comment by PawanOsman** [comment]
@hubaolong3632 why are you spaming all the issues with the same comment? are you okay?! delete all your comments NOW or I will block you
