### ISSUE TITLE
Error getting a new session, please try again later, if the issue persists,

### ISSUE THREAD

**Issue by hubaolong3632** [PawanOsman/ChatGPT#114]
Error getting a new session, please try again later, if the issue persists, 
![image](https://github.com/PawanOsman/ChatGPT/assets/87271391/892e3b07-72d4-421d-9dfa-e43fa9c3f534)

**Comment by dealdot** [comment]
curl https://chat.openai.com/backend-anon/sentinel/chat-requirements

response:
<noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript>

**Comment by hubaolong3632** [comment]
> 卷曲 https://chat.openai.com/backend-anon/sentinel/chat-requirements
> 
> 响应：
> 
> 启用 JavaScript 和 Cookie 以继续

我用的不是node.js吗 ，这个怎么能启用 JavaScript 和 Cookie  ，,麻烦大佬告知

**Comment by hubaolong3632** [comment]
@PawanOsman

**Comment by m00nfly** [comment]
无法从 chatGPT 获取 new session
可能是你服务器访问 chatGPT 网站被限制了，或者是有问题；
尝试直接从你的服务器上访问 chat GPT 的聊天网站，看看是否能否正常聊天？先排除一下服务器IP被 chatGPT 限制的问题。

**Comment by PawanOsman** [comment]
@hubaolong3632 Please use a U.S. VPN. If you are already using one, OpenAI may blocked your IP/VPN IP, please use another VPN/IP.
