### ISSUE TITLE
My VPS is in US，and got this！Please help me

### ISSUE THREAD

**Issue by yichengming** [PawanOsman/ChatGPT#115]
{
  "status": false,
  "error": {
    "message": "Error getting a new session, If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.",
    "type": "invalid_request_error"
  },
  "support": "https://discord.pawan.krd"
}

**Comment by SleepInfinity** [comment]
You may have been blocked from openai because I also tried deploying the api to replit.com and it worked in the beginning but after some requests I started getting this error.

**Comment by Marks-Jack** [comment]
I encountered the same error

**Comment by buhe** [comment]
Same

**Comment by PawanOsman** [comment]
@yichengming, @buhe , @Marks-Jack  Please use a U.S. VPN. If you are already using one, OpenAI may blocked your IP/VPN IP, please use another VPN/IP.

and note that most of the VPS IPs are blocked by OpenAI while they are not residential IPs, so i suggest you to run it locally and use the Cloudflared tunnel to make it public

**Comment by yichengming** [comment]
> @PawanOsman you may need to modify the app so it report the error given by the openai api instead of just giving this response everytime.

But，chatgpt without login works fine on my VPS。

> @PawanOsman you may need to modify the app so it report the error given by the openai api instead of just giving this response everytime.
I have no problem using chatgpt without login on vps.This proves that my IP is not blocked, right?

**Comment by PawanOsman** [comment]
@yichengming, if you're a developer, you must understand the difference between a browser and an API. Using ChatGPT in your browser is not the same as using it via an API!!!!

Cloudflare will block you if you use it as an API!!! not in your browser. Please understand!!!!
