### ISSUE TITLE
Get session id error.

### ISSUE THREAD

**Issue by buhe** [PawanOsman/ChatGPT#117]
I try post https://chat.openai.com/backend-anon/sentinel/chat-requirements , header is oai-device-id: 52dfc2f7-f60e-4061-8013-d7ffe76cd8e7.

But response is 
<img width="1040" alt="截屏2024-04-25 下午4 54 21" src="https://github.com/PawanOsman/ChatGPT/assets/650753/200219eb-48fe-4ebc-adc0-86f2d284bdc1">

Hope it works.

**Comment by SleepInfinity** [comment]
> I try post https://chat.openai.com/backend-anon/sentinel/chat-requirements , header is oai-device-id: 52dfc2f7-f60e-4061-8013-d7ffe76cd8e7.
> 
> But response is <img alt="截屏2024-04-25 下午4 54 21" width="1040" src="https://private-user-images.githubusercontent.com/650753/325542115-200219eb-48fe-4ebc-adc0-86f2d284bdc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzgyNTAsIm5iZiI6MTcxNDAzNzk1MCwicGF0aCI6Ii82NTA3NTMvMzI1NTQyMTE1LTIwMDIxOWViLTQ4ZmUtNGViYy1hZGMwLTg2ZjJkMjg0YmRjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwOTM5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDcxZjc2ZWZmNTc0ZWNmYjI5ZGUzNzk1MTJiOGZhYmZjZGIxZDU3YmRlYTM3YmZmODQxOGQxZjZjMWJiZTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S2EUJUkTeVMSo6aFU47XmUffP1zdwOnMVg-ykvFO6fo">
> 
> Hope it works.

For it to work you should get smth like that:

{'persona': 'chatgpt-noauth', 'arkose': {'required': False, 'dx': None}, 'turnstile': {'required': False}, 'proofofwork': {'required': True, 'seed': '0.5993891310375302', 'difficulty': '02b0b4'}, 'force_login': False, 'token': 'gAAAAABmKiUvPN2F9czG0IV8FjQraxtNR_lzMvq8DQFaMdYeUf-_K2AwhvfyzQbGfEBrmnDaD5t3JGP-HpAH9fSn-4STIIwwqKs3ADSGSidLzNuGjqfmljEKhY18iOiZtlRSj498uD3ePIeBDsJYjcHIoLJoN2DbX7Euzea5FvH7Dri_VbNgyUhwTm6Jkr2I4xeNiuMKZXsDaljfaD8YDbYdUaE3DfQ90ni9p7ShFWz6dRTNU0F5jZh7D9lTHaLLfwMrY2mewg1poQcVoAEmf4VwTxrF5jvHhxmKuGVC-WZdMN5bTGjjuTUFJWOVXkTicVRcKr_YFSP1QUkWq5oYfeZMG53Q7Vv5SPvcqzLOCwRdGxkFRO9qfO6nOBqL02okecr-XZMsVI69xO81XvI-srfDknwzoE40og=='}
