### ISSUE TITLE
i get an error saying my country might not be supported despite it working two days ago 

### ISSUE THREAD

**Issue by mrpotato1107** [PawanOsman/ChatGPT#121]
[2024-04-26 11:52:59 Request: POST /v1/chat/completions 6 messages (stream-enabled)
2024-04-26 11:53:02 Error getting a new session...
2024-04-26 11:53:02 If this error persists, your country may not be supported yet.
2024-04-26 11:53:02 If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.]

it used to work with no issue until two days ago when it started saying that. i tried a vpn and a proxy but it remained the same. im running it as is via docker. i tried reinstalling the docker and reinstalling the API but its not working.

**Comment by mrpotato1107** [comment]
i dont know what to say but it just returned to work somehow..

**Comment by enrikush** [comment]
i still have this issue

**Comment by mrpotato1107** [comment]
it just returned as quickly as it stopped. for some reason it now does it again

**Comment by 2013224691** [comment]
I'm having the same problem. Any ideas on how to fix it? I'm in the US and I'm trying to use a US VPN anyways, but it's not working

**Comment by Master5010** [comment]
Pawan said there is something wrong with the project, he said he's looking into it, no ETA on a fix yet...

**Comment by mrpotato1107** [comment]
there's something i just now discovered. i have my router set so every week my public ip changes or everytime it shutsdown (i forgot how its called) what i discovered is that once my IP changes it starts working again for only two messeges/requests or  prompt or whatever and stops working again until i change my public ip again

**Comment by Master5010** [comment]
> there's something i just now discovered. i have my router set so every week my public ip changes or everytime it shutsdown (i forgot how its called) what i discovered is that once my IP changes it starts working again for only two messeges/requests or prompt or whatever and stops working again until i change my public ip again

Yes I had discovered that too, it seems like cloud flare is the problem, annoying I must say

**Comment by hubaolong3632** [comment]
Error getting a new session, If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.","type":"invalid_request_error I also have this problem, what should I do

**Comment by ocdevcn** [comment]
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.

Why is my stream disabled?
