### ISSUE TITLE
Error while getting new session

### ISSUE THREAD

**Issue by nishantshah977** [PawanOsman/ChatGPT#124]
@PawanOsman It works fine in my localhost. Whne I try to host it on render or shared web hosting it gives following error.

```
error={'message': 'Error getting a new session, If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.', 'type': 'invalid_request_error'}, support='https://discord.pawan.krd')
```

**Steps taken to reproduce**
1. Switched to US location
2. Used US Proxy
3. Waited 24 hours to see if it works

**Comment by 2013224691** [comment]
I'm having the same problem. Any ideas on how to fix it? I'm in the US and I'm trying to use a US VPN anyways, but it's not working.

**Comment by nishantshah977** [comment]
I created my own proxy using python so closed this issue. Thanks for this wonderful project.

**Comment by 2013224691** [comment]
Can you share your python solution please?

**Comment by nishantshah977** [comment]
What I did is used g4f.ai for getting response from model and returned those using flask (like your code does).

Why don't you explore it and create new repo. You project is really awesome and helpful. Hope to see it live again without any error
