### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by QuantumCoderr** [PawanOsman/ChatGPT#125]
I would like to ask a question. How can I add support for other LLMs? For example, gpt-4-turbo, can you give examples please? I would be glad. How was it done?

**Comment by hubaolong3632** [comment]
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.
Request: POST /v1/chat/completions 1 messages (stream-disabled)
Error getting a new session...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN or a U.S. residential proxy.

**Comment by seszele64** [comment]
@hubaolong3632 
what model did you run? 
have you tried using vpn or proxy to make it work?
