### ISSUE TITLE
An error occurred. please try again. Additionally, ensure that your request complies with OpenAI's policy

### ISSUE THREAD

**Issue by hubaolong3632** [PawanOsman/ChatGPT#133]
![image](https://github.com/PawanOsman/ChatGPT/assets/87271391/80fe3f79-4b5a-4500-9ccb-3c3754297247)
{
    "status": false,
    "error": {
        "message": "An error occurred. please try again. Additionally, ensure that your request complies with OpenAI's policy.",
        "type": "invalid_request_error"
    },
    "support": "https://discord.pawan.krd"
}
How should this be resolved

**Comment by deflexable** [comment]
i'm also having this issue, please were you able to resolve this issue?

**Comment by hubaolong3632** [comment]
@PawanOsman

**Comment by armanhi** [comment]
![image](https://github.com/PawanOsman/ChatGPT/assets/2114209/3a24fb56-4693-4a7a-a712-c38049e4e0fd)

This is the error I'm seeing

**Comment by tukangparkir2008** [comment]
i'm also having this issue

**Comment by felipemarinho97** [comment]
This is a fake project? Mine does not works also

**Comment by PawanOsman** [comment]
> This is a fake project? Mine does not works also

all your respect for someone's open-source project is to tell it is fake? you have to use your brain! these type of projects should be updated daily while OpenAI will block the methods we use, and I didn't have time to update it for 2 months!
