### ISSUE TITLE
README should include note about access to hosted API being limited to Patreon supporters

### ISSUE THREAD

**Issue by metomimic** [PawanOsman/ChatGPT#138]
This section https://github.com/PawanOsman/ChatGPT?tab=readme-ov-file#accessing-our-hosted-api does not mention that this is reserved for supporters, which negates the value of this reverse proxy, especially since we're just redirecting money that would otherwise go towards improving the actual model to some middleman who would provide a lower quality experience of the model anyway.

Kind of slimy, btw.

 I can submit a PR for this change as well.

**Comment by PawanOsman** [comment]
@metomimic Our pre-hosted API is free, I didn't mention "Reverse proxy" I mentioned "Accessing Our Hosted API" which we provide our model for free (not OpenAI models)

I hope you understand.
