### ISSUE TITLE
docker: Error response from daemon: manifest for pawanosman/chatgpt:latestd not found: manifest unknown: manifest unknown.

### ISSUE THREAD

**Issue by MeechaPooch** [PawanOsman/ChatGPT#142]
Running on macos m1 brew installed docker 
<img width="666" alt="image" src="https://github.com/PawanOsman/ChatGPT/assets/55720333/cc0fb06f-9569-44bb-8832-e0e9024010ac">

**Comment by anudeepadi** [comment]
it's 'pawanosman/chatgpt:latest'
