### ISSUE TITLE
Error running 'npm start': no 'start' script found

### ISSUE THREAD

**Issue by HePingLaoSan** [PawanOsman/ChatGPT#18]
Based on the documentations, I ran `npm start`, but it didn't work and returned an error message indicating that there is no `start` script. Did I miss something?

**Comment by N00b1X** [comment]
> Based on the documentations, I ran `npm start`, but it didn't work and returned an error message indicating that there is no `start` script. Did I miss something?

I have the same issue. I tried:
`npm rm -g create-react-app
npm install -g create-react-app
npx create-react-app npm my-app`
Everything compiled and ran the localhost server, but when I ran my app that needs to connect to the API it gave me "Request failed with status code: 404", so maybe I am missing something.

**Comment by PawanOsman** [comment]
> Based on the documentations, I ran `npm start`, but it didn't work and returned an error message indicating that there is no `start` script. Did I miss something?

Fixed

**Comment by PawanOsman** [comment]
> > Based on the documentations, I ran `npm start`, but it didn't work and returned an error message indicating that there is no `start` script. Did I miss something?
> 
> I have the same issue. I tried: `npm rm -g create-react-app` `npm install -g create-react-app` `npx create-react-app npm my-app` Everything compiled and ran the localhost server, but when I ran my app that needs to connect to the API it gave me "Request failed with status code: 404", so maybe I am missing something.

this project isn't a react app
