### ISSUE TITLE
How to reset and remember conversations

### ISSUE THREAD

**Issue by muharamdani** [PawanOsman/ChatGPT#2]
First of all, thank you for providing such a good unofficial API for ChatGPT.

I'm only see that only 1 API is provided, is there any API to continue conversations or reset conversations?

Thank you.

**Comment by PawanOsman** [comment]
Thank you for your kind words about the API! I'm glad to hear that you are finding it useful.

Regarding your question about continuing conversations or resetting conversations, I want to mention that the current API does support these features. However, the unofficial ChatGPT client that I'm using (located at https://github.com/PawanOsman/ChatGPT.Net) is in development and does not support conversation, and I'm working on adding these features. I encourage you to keep an eye on that repository for updates that may include these capabilities.

**Comment by PawanOsman** [comment]
Now it's supported you can use the `id` query parameter to set the conversation id
