### ISSUE TITLE
How to define the number of words returned

### ISSUE THREAD

**Issue by Zen33** [PawanOsman/ChatGPT#20]
I resume that the max_tokens is, but when I set a little larger, the result is empty.

**Comment by PawanOsman** [comment]
the model's supported tokens are 4097, your prompt and your completion tokens must not be greater than 4097

example:
if your prompt tokens are 150
you must calculate it like this
4097 - 150 = 3947
means you can't set max_tokens greater than 3947

your prompt tokens + your max_tokens = 4097

**Comment by Zen33** [comment]
Thank you for your reply:)
