### ISSUE TITLE
about ip limitation

### ISSUE THREAD

**Issue by symbuzzer** [PawanOsman/ChatGPT#23]
Every time the mobile internet is reconnected in Turkey and the modem restarts on cable internet, the ip address changes. That's why we need to get the key again.

Is it possible to change the limitation of the IP address with another alternative limitation method?

**Comment by PawanOsman** [comment]
Hey, unfortunately, we can't do anything with dynamic IPs, the IP lock system is to prevent Abuse usage and we can't remove that
