### ISSUE TITLE
Public Proxy: "No bypass servers available. please wait 5 mins and try again."

### ISSUE THREAD

**Issue by sam-hieken** [PawanOsman/ChatGPT#25]
Hello,

I'm trying to use the public proxy (https://api.pawan.krd/) with [the unofficial ChatGPT API](https://www.npmjs.com/package/chatgpt#access-token), but I'm running into a 500 error ("No bypass servers available. please wait 5 mins and try again.") when calling /backend-api/ endpoints. I attached a screenshot of my output after doing the request in Insomnia below.

![image](https://user-images.githubusercontent.com/99104112/232626592-553cbd42-e8e2-4a1a-8f01-08a58d0a58f0.png)

Thank you.

**Comment by PawanOsman** [comment]
can you test it now?

**Comment by sam-hieken** [comment]
@PawanOsman Up and running, thanks. Closing issue.
