### ISSUE TITLE
403

### ISSUE THREAD

**Issue by hyoutom** [PawanOsman/ChatGPT#26]
I am trying to use proxies on servers in Hong Kong and Japan https://api.pawan.krd/v1/completions ,

But they were all rejected, and it works normally under localhost. What can I do to use proxies on servers in Hong Kong and Japan https://api.pawan.krd/v1/completions

**Comment by PawanOsman** [comment]
Maybe your IP blacklisted by Cloudflare, make sure to use a server with dedicated IP address
