### ISSUE TITLE
LangChain: Unable to parse response from reverse proxy

### ISSUE THREAD

**Issue by mongj** [PawanOsman/ChatGPT#29]
It seems like [LangChain](https://github.com/hwchase17/langchain) is unable to parse the response returned by the reverse proxy as the json object is missing the `id` and `created` fields. Tested with the 2 fields added and it works well. Would it be possible to add in these 2 fields in the json response? The values for these 2 keys can be `null`.

**OpenAI's official API:**
```
{
  "id": "cmpl-7ANU4Oi82ua4aJZJxK88r7AGqpxzc",
  "object": "text_completion",
  "created": 1682707908,
  "model": "text-ada-001",
  "choices": [
    {
      "text": "\n\nYes, this is a test.",
      "index": 0,
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 10,
    "completion_tokens": 9,
    "total_tokens": 19
  }
}
```

**Reverse proxy:**
```
{
  "object": "text_completion",
  "model": "text-davinci-003",
  "choices": [
    {
      "text": " This is a test.",
      "index": 0,
      "finish_reason": "stop",
      "logprobs": null
    }
  ],
  "usage": {
    "prompt_tokens": 10,
    "completion_tokens": 5,
    "total_tokens": 15
  }
}
```

**Comment by PawanOsman** [comment]
Thank you, fixed it yesterday

**Comment by scryptic1** [comment]
Even with this change Langchain is unable to work, returning http error code 503

**Comment by PawanOsman** [comment]
Langchain currently isn't supported by our API
