### ISSUE TITLE
responses come up empty

### ISSUE THREAD

**Issue by nobodyatandnothing** [PawanOsman/ChatGPT#3]

**Comment by Kowkodivka** [comment]
same

**Comment by Kowkodivka** [comment]
https://api.pawan.krd/chat/gpt?text=+h&lang=en

response:
data: { state: false, error: 'Something went worng!' }

**Comment by nsde** [comment]
same. this doesn't work.

**Comment by PawanOsman** [comment]
Fixed

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/218280539-d5846f29-7eb9-42c9-8013-5877a6386098.png)

**Comment by MahdeenSky** [comment]
Opening it up because the same thing happens now, with certain prompts.
