### ISSUE TITLE
post request to https://api.pawan.krd/v1/chat/completions not fully complete read body

### ISSUE THREAD

**Issue by the-thirteenth-fox** [PawanOsman/ChatGPT#32]
This filed when I use OpenAI API works well: "model": "gpt-3.5-turbo", but when I changed it into current API, the response contains this:  {"id":"cmpl-...,"created":1683331180268,"model":"text-davinci-003", the main problem that fields are not readable by this API.

**Comment by PawanOsman** [comment]
can you give us a reproducible example?

**Comment by the-thirteenth-fox** [comment]
<img width="1255" alt="Снимок экрана 2023-05-08 в 01 15 33" src="https://user-images.githubusercontent.com/44783405/236705314-e3cb403e-f5a0-48e2-a035-87a54526d037.png">

**Comment by the-thirteenth-fox** [comment]
@PawanOsman

**Comment by sharifjameel90** [comment]
> <img alt="Снимок экрана 2023-05-08 в 01 15 33" width="1255" src="https://user-images.githubusercontent.com/44783405/236705314-e3cb403e-f5a0-48e2-a035-87a54526d037.png">

Since to do 100% uptime and give everyone to use the api it automatically switches between models to keep 100% uptime
