### ISSUE TITLE
Is this really chatgpt?

### ISSUE THREAD

**Issue by qxb3** [PawanOsman/ChatGPT#34]
I tried this but its giving me weird result that chatgpt would no way going to say.

# Code

> Prompt: are u chatgpt?

```js
const response = await ai.createCompletion({
  model: 'text-davinci-003',
  prompt: 'are u chatgpt?',
  temperature: 0.7,
        max_tokens: 256,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0
})
```

### This repo:

```
ChatGPT is a chatbot platform developed by OpenAI. It uses natural language processing (NLP) to create automated conversations with users, allowing them to ask questions and get answers in real-time.
```

### Official Chatgpt:

```
Yes, I am ChatGPT, a large language model trained by OpenAI, based on the GPT-3.5 architecture. How can I assist you today?
```

**Comment by PawanOsman** [comment]
`text-davinci-003` is not ChatGPT

**Comment by qxb3** [comment]
oh i see, is the chatgpt model are not opened to the public?

**Comment by nicermak** [comment]
Use gpt-3.5-turbo instead

**Comment by qxb3** [comment]
@nicermak still the same, now it says he's john for some reason

**Comment by nacho00112** [comment]
ChatGPT is the page at chat.openai.com, it uses the models from the API, but is not a model of the API

**Comment by nacho00112** [comment]
> @nicermak still the same, now it says he's john for some reason

Hahahaha may be cause of the parameters

**Comment by nsde** [comment]
> oh i see, is the chatgpt model are not opened to the public?

The model used for ChatGPT is `gpt-3.5-turbo`. It is open.

**Comment by nsde** [comment]
> @nicermak still the same, now it says he's john for some reason

That is absolutely expected.
Just make up a conversation using the `messages` parameter, where the AI tells the user that its name is ChatGPT.

Learn more here:
https://platform.openai.com/docs/api-reference/chat/create

**Comment by PawanOsman** [comment]
> oh i see, is the chatgpt model are not opened to the public?

now you can use `gpt-3.5-turbo`

**Comment by grupoquantum** [comment]
How long for the key to expire?

**Comment by PawanOsman** [comment]
> How long for the key to expire?

our keys won't expire
