### ISSUE TITLE
Support for fine-tuning and using fine-tuned models

### ISSUE THREAD

**Issue by nacho00112** [PawanOsman/ChatGPT#36]
The API support fine-tuning models or using already fine-tuned ones? If not, it will do or could do one of this two things in the future?

**Comment by altacountbabi** [comment]
I dont think fine tuning is coming any time soon, this api just reverse engineers some websites that provide text generation, it doesnt actually use the openai api with paid api keys

However you could try to fine tune a model like gpt-2 or gpt-j which are open source tho you will need a decent gpu.

**Comment by nacho00112** [comment]
Now i understand it would certainly be a hard thing to add to the API, thanks for helping
