### ISSUE TITLE
Deploy on vercel

### ISSUE THREAD

**Issue by Crazygird** [PawanOsman/ChatGPT#42]
How do I deploy this on vercel?

**Comment by deezed420** [comment]
You can't.

**Comment by Crazygird** [comment]
Wow, that was anticlimactic.

**Comment by SoftCreatR** [comment]
In theory, you can. But you won't be able to connect to the OpenAI-Service, because Cloudflare'll block it.

**Comment by cliouo** [comment]
> How do I deploy this on Vercel?

Maybe you can try this: https://github.com/cliouo/FreeGPT35-Vercel
