### ISSUE TITLE
"Invalid request, or Something went wrong!",

### ISSUE THREAD

**Issue by VatsaDev** [PawanOsman/ChatGPT#46]
So I was trying to use a http://127.0.0.1:5000/ local flask app with the python implementation, and I got the error for the ip address, and that was when I set it to http://127.0.0.1:5000/, but now all i get is 

```
{
  "status": false,
  "error": {
    "message": "Invalid request, or Something went wrong!",
    "type": "invalid_request_error"
  }
}
```

why is that?

**Comment by martysl** [comment]
use endpoint from discord, this one u probably put is on maintenance (unfiltered only work right now)

**Comment by martysl** [comment]
curl --location 'https://api.pawan.krd/unfiltered/v1/chat/completions' \
--header 'Authorization: Bearer pk-*****your API KEY' \
--header 'Content-Type: application/json' \
--data '{
    "model": "gpt-3.5-turbo",
    "max_tokens": 100,
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant  ."
        },
        {
            "role": "user",
            "content": "YOUR PROMPT HERE."
        }
    ]
}'
