### ISSUE TITLE
getting bad gateway error when using python

### ISSUE THREAD

**Issue by Ccode-lang** [PawanOsman/ChatGPT#5]
If I use a browser it works though.

**Comment by Ccode-lang** [comment]
I forgot to close this I'll do that now.

**Comment by joalricha869** [comment]
how is this solved? i need help with this too

**Comment by mediaexplorer74** [comment]
Pawan Osman, hi. What's happen? Are you cancelled this project?...

**Comment by joalricha869** [comment]
the site works but the API returns a JSON error help
