### ISSUE TITLE
This tool doesn't work.

### ISSUE THREAD

**Issue by hongyi-zhao** [PawanOsman/ChatGPT#6]
I try to test this project using the example [here](https://github.com/PawanOsman/ChatGPT#python) but failed:

```python
(datasci) werner@X10DAi:~$ ipython
Python 3.11.1 (main, Dec 22 2022, 17:06:07) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import requests
   ...: 
   ...: def get_response(text, lang):
   ...:   params = {'text': text, 'lang': lang}
   ...:   response = requests.get('https://api.pawan.krd/chat/gpt', params=param
   ...: s)
   ...:   return response.json()
   ...: 
   ...: response = get_response('Hello', 'en')
   ...: print(response)
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File ~/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File ~/.pyenv/versions/3.11.1/lib/python3.11/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File ~/.pyenv/versions/3.11.1/lib/python3.11/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File ~/.pyenv/versions/3.11.1/lib/python3.11/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Cell In[1], line 8
      5   response = requests.get('https://api.pawan.krd/chat/gpt', params=params)
      6   return response.json()
----> 8 response = get_response('Hello', 'en')
      9 print(response)

Cell In[1], line 6, in get_response(text, lang)
      4 params = {'text': text, 'lang': lang}
      5 response = requests.get('https://api.pawan.krd/chat/gpt', params=params)
----> 6 return response.json()

File ~/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Is there any problem with my usage?

**Comment by mediaexplorer74** [comment]
> I try to test this project using the example [here](https://github.com/PawanOsman/ChatGPT#python) but failed:
> 
> ```python
> (datasci) werner@X10DAi:~$ ipython
> Python 3.11.1 (main, Dec 22 2022, 17:06:07) [GCC 12.2.0]
> Type 'copyright', 'credits' or 'license' for more information
> IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import requests
>    ...: 
>    ...: def get_response(text, lang):
>    ...:   params = {'text': text, 'lang': lang}
>    ...:   response = requests.get('https://api.pawan.krd/chat/gpt', params=param
>    ...: s)
>    ...:   return response.json()
>    ...: 
>    ...: response = get_response('Hello', 'en')
>    ...: print(response)
> ---------------------------------------------------------------------------
> JSONDecodeError                           Traceback (most recent call last)
> File ~/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
>     970 try:
> --> 971     return complexjson.loads(self.text, **kwargs)
>     972 except JSONDecodeError as e:
>     973     # Catch JSON-related errors and raise as requests.JSONDecodeError
>     974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
> 
> File ~/.pyenv/versions/3.11.1/lib/python3.11/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
>     343 if (cls is None and object_hook is None and
>     344         parse_int is None and parse_float is None and
>     345         parse_constant is None and object_pairs_hook is None and not kw):
> --> 346     return _default_decoder.decode(s)
>     347 if cls is None:
> 
> File ~/.pyenv/versions/3.11.1/lib/python3.11/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
>     333 """Return the Python representation of ``s`` (a ``str`` instance
>     334 containing a JSON document).
>     335 
>     336 """
> --> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>     338 end = _w(s, end).end()
> 
> File ~/.pyenv/versions/3.11.1/lib/python3.11/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
>     354 except StopIteration as err:
> --> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
>     356 return obj, end
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> JSONDecodeError                           Traceback (most recent call last)
> Cell In[1], line 8
>       5   response = requests.get('https://api.pawan.krd/chat/gpt', params=params)
>       6   return response.json()
> ----> 8 response = get_response('Hello', 'en')
>       9 print(response)
> 
> Cell In[1], line 6, in get_response(text, lang)
>       4 params = {'text': text, 'lang': lang}
>       5 response = requests.get('https://api.pawan.krd/chat/gpt', params=params)
> ----> 6 return response.json()
> 
> File ~/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
>     971     return complexjson.loads(self.text, **kwargs)
>     972 except JSONDecodeError as e:
>     973     # Catch JSON-related errors and raise as requests.JSONDecodeError
>     974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
> --> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> Is there any problem with my usage?

Switch to normal language (C#). Python is not cool thing.

**Comment by hongyi-zhao** [comment]
I'm on Linux, and `C#` is a Microsoft based language, IIRC. More precisely, I'm not familiar with it :-(

**Comment by PawanOsman** [comment]
We updated the API endpoint check readme for docs

**Comment by hongyi-zhao** [comment]
1. According to the guidance [here](https://github.com/PawanOsman/ChatGPT#use-our-hosted-api-reverse-proxy), I obtained my API key from the #Bot channel by sending /key command, but still failed when running the following test:

```shell
$ curl --location 'https://api.pawan.krd/v1/images/generations' --header 'Authorization: Bearer pk-xxx' --header 'Content-Type: application/json' --data '{
    "prompt": "a photo of a happy corgi puppy sitting and facing forward, studio light, longshot",
    "n": 1,
    "size": "1024x1024"
}'
{"status":false,"error":"Invalid API key","hint":"You can get an API key from https://discord.pawan.krd","info":"https://gist.github.com/PawanOsman/72dddd0a12e5829da664a43fc9b9cf9a","support":"https://discord.pawan.krd"}
```
2. Does the provided key support GPT-4?

**Comment by PawanOsman** [comment]
make sure your API Key `pk-xxx` is correct , no currently GPT-4 isn't supported

**Comment by hongyi-zhao** [comment]
Thank you for pointing this out. The above problem is caused by the loss of some API key characters during the copying and pasting process.
