### ISSUE TITLE
Incorrect API key provided

### ISSUE THREAD

**Issue by Allamaris0** [PawanOsman/ChatGPT#65]
```
import openai

openai.api_key = my_key
openai.api_base = 'https://api.pawan.krd/v1'


response = openai.completions.create(
  model="text-davinci-003",
  prompt="Human: Hello\nAI:",
  temperature=0.7,
  max_tokens=256,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0,
  stop=["Human: ", "AI: "]
)

print(response.choices[0].text)
```

openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: pk-MNLTc***************************************CqBD. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

The same error, when I use openai.api_base = 'https://api.pawan.krd/pai-001-light-beta/v1'

BTW you should update your README because openai.Completion is no longer support with openai higher than 0.28

**Comment by Zeroocooloverride** [comment]
Have the same Error

**Comment by donburgareli** [comment]
Just to make sure, y'all using the the Pawan's API key, not the openAI one, right ?
Also, check in #models channel to make sure your role allow the model usage.

**Comment by Zeroocooloverride** [comment]
Hi there, im not a tech savy here. Would like to understand what could possibly be the issue when im using ChatOllama in Langflow everything works fine, but when i use Ollama Embedding, it triggers the corporate network security block? The model has been downloaded locally in my PC.

Update: Found out Ollama Embedding doesnt work if i disconnect the netwrok access. 

Update solution found: 
1. Stop Ollama.exe 
2. Set OLLAMA_HOST env variable to value 0.0.0.0 (listening to all port) 
3. run ollama serve in power shell instead to start ollama service.
