### ISSUE TITLE
invalid_request_error from self-hosted API

### ISSUE THREAD

**Issue by changchiyou** [PawanOsman/ChatGPT#71]
![Screenshot_2024-04-05-12-47-33-53_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/PawanOsman/ChatGPT/assets/46549482/fafc9185-7364-4bbb-b888-6294ecb98fa6)

![Screenshot_2024-04-05-12-47-46-14_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/PawanOsman/ChatGPT/assets/46549482/8ef12551-cc59-4e4d-b90f-287cc0cd69e5)

**Comment by changchiyou** [comment]
After I uncommented:

https://github.com/PawanOsman/ChatGPT/blob/main/src%2Fapp.ts#L236-L236

![Screenshot_2024-04-05-13-39-30-91_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/PawanOsman/ChatGPT/assets/46549482/d17902bb-568d-4617-b256-1c7d18027b36)

**Comment by PawanOsman** [comment]
Please double-check your request. It should be an issue from your request that the server can't read your payload messages. As you can see in the server logs, it says 0 messages, and the error occurred while mapping the messages.

**Comment by changchiyou** [comment]
![Screenshot_2024-04-05-17-06-02-88_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/PawanOsman/ChatGPT/assets/46549482/57019983-6a41-427f-afed-ae9f7db00490)
