### ISSUE TITLE
When accessing the website, it was detected that I am using a VPN.

### ISSUE THREAD

**Issue by huhu415** [PawanOsman/ChatGPT#75]
I'm sorry to bother you, but I encountered some issues when trying to convert your project into golang. Here is my golang [code.](https://github.com/huhu415/chatGPT). When I send a request to /backend-anon/sentinel/chat-requirements, the  received is not json, but html, with a paragraph that reads:
`          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M12 9v3.75m0-10.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.75c0 5.592 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.57-.598-3.75h-.152c-3.196 0-6.1-1.249-8.25-3.286zm0 13.036h.008v.008H12v-.008z"
          />
        </svg>
        <p>Unable to load site</p>
      </div>
      <span class="explanation">
        Please try again later. If you are using a VPN, try turning it off.
        Check the
        <a href="https://status.openai.com/" target="_new">status page</a> for
        information on outages.
      </span>
      <br />
      <span class="explanation"> [IP:47.236.168.62 | Ray ID:870a789bfe8d3e36] </span>
    </div>
  <script>(function(){if (!document.body) return;var js = "window['__CF$cv$params']={r:'870a789bfe8d3e36',t:'MTcxMjQ5NzY2My4zODcwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body>
</html>
`
Thank you for looking, if this project works well, I will attach a byline to your project
by the way , The same computer can run your project, but mine golang can't

**Comment by PawanOsman** [comment]
You should use a good VPN, I recommend [Windscribe](https://windscribe.com/).

**Comment by huhu415** [comment]
In fact, the Linux host I use is in Singapore, and the host can access chatgpt without using a VPN, and you may not have seen my last sentence: "by the way, The same computer can run your project, but mine golang can't"
At the same time, I also found a golang project that implements similar functionality. I'm planning to take a look at its code.

**Comment by huhu415** [comment]
I found the problem, which is that OpenAI detects TLS signatures. I need to find a way to simulate TLS signatures.

**Comment by PawanOsman** [comment]
@huhu415, unfortunately, it's not about TLS signatures. I have worked on bypassing OpenAI's bot protections for more than a year, so I understand how it works. They were using TLS signatures before, but not anymore.

This project allows the use of ChatGPT without an account, which isn't available in all countries yet. Even if it is supported in your country, you would need to run it on your local machine because OpenAI (via Cloudflare) blocks the IPs of hosting providers. That's why I suggested using a reliable VPN, as most IPs from VPN/VPS/hosting providers are blocked by OpenAI.

Note that when I say it's not available in all countries yet, I'm not referring to ChatGPT itself. You may be able to use ChatGPT with your account, but using it without an account is a new thing by OpenAI.

**Comment by PawanOsman** [comment]
@huhu415  you're using Alibaba Cloud, it's likely that your IP has been blocked by OpenAI due to your use of a VPS/host. Approximately a year ago, OpenAI blocked the IP ranges of AWS, Oracle Cloud, and most other cloud services, preventing any access to chat.openai.com.

**Comment by huhu415** [comment]
Why can I run your JavaScript project on the same VPS, but not my Golang project?
 If my VPS is blocked, then no project on this VPS can access OpenAI's services.

**Comment by huhu415** [comment]
Just succeeded once, it's definitely not because of TLS, it should be due to the order of request headers, and then it's about sending the data inside the JSON, it can be missing, but it cannot be empty, like "".

**Comment by PawanOsman** [comment]
as i said they are not using TLS signature verification anymore
