### ISSUE TITLE
Response stream format may be wrong for some reason

### ISSUE THREAD

**Issue by dealdot** [PawanOsman/ChatGPT#80]
![4061712559594_ pic](https://github.com/PawanOsman/ChatGPT/assets/19355027/bcfccb73-0bd6-41f2-863e-a50805d33174)
![4051712558833_ pic](https://github.com/PawanOsman/ChatGPT/assets/19355027/d2dd1eaa-05e2-4598-a9db-26c184ac62d2)

When I using  JSON.parse(chunk) it may throw error , when I debug I found that in some case, I got the following stream format:
![4071712560257_ pic](https://github.com/PawanOsman/ChatGPT/assets/19355027/ca282159-c57b-4ae8-8ab3-19c3d9da605b)

This prints two json string in one chunk while others(mostly) just print one json string in one chunk, the latter format is what I want, as the image shows following:

![4081712560404_ pic](https://github.com/PawanOsman/ChatGPT/assets/19355027/a8eec587-3d27-46db-a66e-a2bef6df68a0)

**Comment by PawanOsman** [comment]
@dealdot Please use `Postman` to verify, as it will confirm if two pieces of data are provided within a single chunk.

**Comment by dealdot** [comment]
Postman looks good, I use next.js for api query


```
const response = await fetch(`${process.env.BACKGROUND_API_BASE_URL}/api/chat-free`, {
        headers: {
            "Content-Type": "application/json", 
            "Authorization": `Bearer ${(payload as any).token}`
        },
        method: "POST",
        body: JSON.stringify(payload)
    })


and then process:

const stream = new ReadableStream({
            async start(controller) {
                for await (const chunk of response.body as any) {
                    let decodeChunk = decoder.decode(chunk)
                    console.log('stream --:', decodeChunk)
                    controller.enqueue(encoder.encode(decodeChunk)) //一定要 encode
                }
                //当数据传输完成后关闭流
                controller.close()
            }
        })
        return stream

```
The log for decodeChunk looks like 

    
![4121712576612_ pic](https://github.com/PawanOsman/ChatGPT/assets/19355027/74bee5e3-06c6-4c93-bdef-17298973a085)

What is the possible issue may be here ? thanks

**Comment by PawanOsman** [comment]
try to use axios instead of fetch

**Comment by dealdot** [comment]
Alright, I'll give it a shot. I'm curious, does the API Free Reverse Proxy support tracking? For instance, can it track using the conversation using request parameter  like  "parentMessageId"?
