### ISSUE TITLE
You can't use another key on this is address 25

### ISSUE THREAD

**Issue by yingnengd** [PawanOsman/ChatGPT#81]
OPENAI_API_BASE | https://api.pawan.krd/v1/

OPENAI_API_DOMAIN | https://api.pawan.krd/

discord applying key
:pk-rlOWeBRqhM**************

but the telegram not working 
it display:
"You can't use another key on this is address 253.102.157.193"

I use the baseurl and api key for this project:[https://github.com/TBXark/ChatGPT-Telegram-Workers]

Could u please tell me
what about  something wrong?

**Comment by PawanOsman** [comment]
Please note that our API keys are IP-locked, meaning you cannot use two keys on the same IP address. Do you have more than one key? Or perhaps your app is hosted on a shared server, which gives the same IP to multiple users. To address this, you can create a ticket in our [Discord community](https://discord.pawan.krd) so I can investigate your issue and assist in resolving it.
