### ISSUE TITLE
How to get track off the same chat while using the API ?

### ISSUE THREAD

**Issue by TechyCSR** [PawanOsman/ChatGPT#83]
I am using the python with API to for chat completion , I found that I can track off the same chat after every request , which leads to no chat history for  further responses , that means every times its starts new chat . that really sucks !!

**Comment by PawanOsman** [comment]
@TechyCSR, this API functions the same as the official OpenAI API, which utilizes the messages array to include all chat history. Therefore, you must send the chat history with your request every time. Please read the official [OpenAI Chat API Reference](https://platform.openai.com/docs/api-reference/chat) for more information.

**Comment by demon2202** [comment]
@TechyCSR ,  In Python, when you're making a chat application using an API, you need to make sure the conversation flows smoothly. To do this, you give each chat session a special code. You save this code along with the conversation in a way you can easily find it later. Then, whenever someone wants to continue chatting, you use this code to find the conversation and pick up where it left off. You can use tools like Flask or Django for websites or Pyrogram for Telegram bots to help you with this. For more information read the official OpenAI Chat API Reference

**Comment by dealdot** [comment]
When I  send the new chat with history for my request every time, it response me the former response , that is not what we want to be.

this is the first time request param

![WeChat82485826362eccca838391dc7d962efa](https://github.com/PawanOsman/ChatGPT/assets/19355027/19c24981-2b22-4356-90c0-fa63aea78a4f)

this is the first time response

![WeChatb73bc42ffb51bb14eb4125d36955c4a0](https://github.com/PawanOsman/ChatGPT/assets/19355027/ef40978c-f8cb-459a-bece-c822e1d6cd64)

this is the following  request param

![WeChatabea882575e8d7676f4210263da1f314](https://github.com/PawanOsman/ChatGPT/assets/19355027/1e796de2-486b-4bc8-9327-2672a9f62272)

**this is the following response, we can see it response the first response as the following response here**

`
{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "hi",
    "choices": [
        {
            "delta": {
                "content": "hi"
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "Hello! How can I assist you today?",
    "choices": [
        {
            "delta": {
                "content": "Hello! How can I assist you today?"
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I",
    "choices": [
        {
            "delta": {
                "content": "I"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm",
    "choices": [
        {
            "delta": {
                "content": "I'm"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just",
    "choices": [
        {
            "delta": {
                "content": "I'm just"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a",
    "choices": [
        {
            "delta": {
                "content": "I'm just a"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program",
    "choices": [
        {
            "delta": {
                "content": "I'm just a program"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program,",
    "choices": [
        {
            "delta": {
                "content": "I'm just a program,"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so",
    "choices": [
        {
            "delta": {
                "content": "I'm just a program, so"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I",
    "choices": [
        {
            "delta": {
                "content": "I'm just a program, so I"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don",
    "choices": [
        {
            "delta": {
                "content": "I'm just a program, so I don"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't",
    "choices": [
        {
            "delta": {
                "content": "I'm just a program, so I don't"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have",
    "choices": [
        {
            "delta": {
                "content": "I'm just a program, so I don't have"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings",
    "choices": [
        {
            "delta": {
                "content": " feelings"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in",
    "choices": [
        {
            "delta": {
                "content": " in"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the",
    "choices": [
        {
            "delta": {
                "content": " the"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same",
    "choices": [
        {
            "delta": {
                "content": " same"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way",
    "choices": [
        {
            "delta": {
                "content": " way"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans",
    "choices": [
        {
            "delta": {
                "content": " humans"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do",
    "choices": [
        {
            "delta": {
                "content": " do"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do,",
    "choices": [
        {
            "delta": {
                "content": ","
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but",
    "choices": [
        {
            "delta": {
                "content": " but"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I",
    "choices": [
        {
            "delta": {
                "content": " I"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm",
    "choices": [
        {
            "delta": {
                "content": "'m"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here",
    "choices": [
        {
            "delta": {
                "content": " here"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and",
    "choices": [
        {
            "delta": {
                "content": " and"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready",
    "choices": [
        {
            "delta": {
                "content": " ready"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to",
    "choices": [
        {
            "delta": {
                "content": " to"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help",
    "choices": [
        {
            "delta": {
                "content": " help"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you",
    "choices": [
        {
            "delta": {
                "content": " you"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with",
    "choices": [
        {
            "delta": {
                "content": " with"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever",
    "choices": [
        {
            "delta": {
                "content": " whatever"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you",
    "choices": [
        {
            "delta": {
                "content": " you"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need",
    "choices": [
        {
            "delta": {
                "content": " need"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need.",
    "choices": [
        {
            "delta": {
                "content": "."
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How",
    "choices": [
        {
            "delta": {
                "content": " How"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about",
    "choices": [
        {
            "delta": {
                "content": " about"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you",
    "choices": [
        {
            "delta": {
                "content": " you"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you?",
    "choices": [
        {
            "delta": {
                "content": "?"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How",
    "choices": [
        {
            "delta": {
                "content": " How"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How's",
    "choices": [
        {
            "delta": {
                "content": "'s"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How's your",
    "choices": [
        {
            "delta": {
                "content": " your"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How's your day",
    "choices": [
        {
            "delta": {
                "content": " day"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How's your day going",
    "choices": [
        {
            "delta": {
                "content": " going"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How's your day going?",
    "choices": [
        {
            "delta": {
                "content": "?"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How's your day going?",
    "choices": [
        {
            "delta": {
                "content": ""
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How's your day going?",
    "choices": [
        {
            "delta": {
                "content": ""
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a program, so I don't have feelings in the same way humans do, but I'm here and ready to help you with whatever you need. How about you? How's your day going?",
    "choices": [
        {
            "delta": {
                "content": ""
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}{
    "id": "chatcmpl-uA0TVuN1JK233vcUi50hGKBdLFJY",
    "created": 1712813900114,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "choices": [
        {
            "delta": {
                "content": ""
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}
`

**Comment by PawanOsman** [comment]
@dealdot please create a new issue, your issue is not related to this one

And please use code blocks when you share a long response or a code

**Comment by TechyCSR** [comment]
@PawanOsman  @demon2202
Thx ,  got it dev's.
