### ISSUE TITLE
error AttributeError: 'NoneType' object has no attribute 'prompt_tokens'

### ISSUE THREAD

**Issue by xiangpingjiang** [PawanOsman/ChatGPT#84]
![image](https://github.com/PawanOsman/ChatGPT/assets/45722758/11e48e0b-5ef6-44de-9b28-f7562d13cad0)

I use the docker setup, but got the error 'NoneType' object has no attribute 'prompt_tokens'

**Comment by PawanOsman** [comment]
the line with the error is from your own code,

![image](https://github.com/PawanOsman/ChatGPT/assets/8727627/164f8d45-1c6d-435a-bda6-1c0a47031c0a)

you have to handle the request and response errors yourself, this isn't an issue from this project

**Comment by xiangpingjiang** [comment]
> the line with the error is from your own code,
> 
> ![image](https://private-user-images.githubusercontent.com/8727627/321319169-164f8d45-1c6d-435a-bda6-1c0a47031c0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjY5NzksIm5iZiI6MTcxMjc2NjY3OSwicGF0aCI6Ii84NzI3NjI3LzMyMTMxOTE2OS0xNjRmOGQ0NS0xYzZkLTQzNWEtYmRhNi0xYzBhNDcwMzFjMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMTYzMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFiZjZiNjYwZDcwNTg2MzVjOTdlMWI5NmQ4MGJkYTllYzZkN2Q3MmJkMDYxNzlkNWFlN2Y4ZGQ3OWEzNmFjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HYjVg6gjn9VXSw_HJ0ryL-Ik-OwuuB2d8b_2t_5jrk8)
> 
> you have to handle the request and response errors yourself, this isn't an issue from this project


sorry, I want to submit the issue to  another project in fact
