### ISSUE TITLE
Tracking conversation response bug

### ISSUE THREAD

**Issue by dealdot** [PawanOsman/ChatGPT#86]
When I send the new chat with history for my request every time, it response me the former response , that is not what we want it to be.

this is the first time request param:

![WeChat3618b89dcc3f347056595c86dff1ea19](https://github.com/PawanOsman/ChatGPT/assets/19355027/e4819bec-4a30-4788-a674-b7a9021b76a8)

this is the first time response:

![WeChat7924a41a99a29cc2098bafd0fd2a47c6](https://github.com/PawanOsman/ChatGPT/assets/19355027/cc741c5e-8753-4696-b297-35dbbb07ea04)

while this is the following request param:

![WeChat6867add237ab4f403cc1f3d2d6ff9651](https://github.com/PawanOsman/ChatGPT/assets/19355027/cbbfbdc8-354f-4ecf-9d9c-349c75e28358)

**this is the following response, we can see it response the first response as the following response here**

{
    "id": "chatcmpl-owvp8S7mqMjsb78RIOzVu4FlXcsb",
    "created": 1712821485062,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "hi",
    "choices": [
        {
            "delta": {
                "content": "hi"
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}{
    "id": "chatcmpl-owvp8S7mqMjsb78RIOzVu4FlXcsb",
    "created": 1712821485062,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "Hello! How can I assist you today?",
    "choices": [
        {
            "delta": {
                "content": "Hello! How can I assist you today?"
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}
.
.
**ellipsis some response here**
.
.
{
    "id": "chatcmpl-owvp8S7mqMjsb78RIOzVu4FlXcsb",
    "created": 1712821485062,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a collection of digital circuits and code, so I don't have feelings like humans do. But I'm here and ready to help you with whatever you need! How about you? How are you doing today?",
    "choices": [
        {
            "delta": {
                "content": "?"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}{
    "id": "chatcmpl-owvp8S7mqMjsb78RIOzVu4FlXcsb",
    "created": 1712821485062,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "I'm just a collection of digital circuits and code, so I don't have feelings like humans do. But I'm here and ready to help you with whatever you need! How about you? How are you doing today?",
    "choices": [
        {
            "delta": {
                "content": ""
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}

**Comment by PawanOsman** [comment]
@dealdot, are you sure you're using this project? And have you not modified it locally? Because I see a "text" property in the chunk responses, which we don't have in our project, and I couldn't replicate the issue you're talking about.
