### ISSUE TITLE
Response break with "finish_reason": "stop"  and then go with    "finish_reason": null   after

### ISSUE THREAD

**Issue by dealdot** [PawanOsman/ChatGPT#88]
I request the Multiplication of three large numbers.

the request params:

![WeChatcf6826371d1e2cfa00b216cd050eabed](https://github.com/PawanOsman/ChatGPT/assets/19355027/a2719986-29b1-479a-84e3-5dde49c2a9d2)

the response stream parts (which breaks for "finish_reason": "stop", is this the right process?)

ignore the "text" property , I just add it for some test
......
{
    "id": "chatcmpl-2Qo2IqU7T8RRv8Qb9j1D8tNYLQCm",
    "created": 1712892245051,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "这是一个相当大的乘法运算，让我来计算一下。稍等片刻。", //ignore
    "choices": [
        {
            "delta": {
                "content": ""
            },
            "index": 0,
            "finish_reason": "stop"
        }
    ]
}
{
    "id": "chatcmpl-2Qo2IqU7T8RRv8Qb9j1D8tNYLQCm",
    "created": 1712892245051,
    "object": "chat.completion.chunk",
    "model": "gpt-3.5-turbo",
    "text": "计", //ignore
    "choices": [
        {
            "delta": {
                "content": "计"
            },
            "index": 0,
            "finish_reason": null
        }
    ]
}
.....

**Sometimes, it break more than 2 times**

**Comment by PawanOsman** [comment]
@dealdot, I asked you before and I ask you again, are you sure you're using this project? And have you not modified it locally? Because I see a "text" property in the chunk responses, which we don't have in our project.

**Comment by dealdot** [comment]
Yes, your project. As I said as above just ignore the text property , which I added for test reason , code here

![WeChat3280bf7878873a4d37d4a49233e603d4](https://github.com/PawanOsman/ChatGPT/assets/19355027/892dc291-648d-4170-b7f5-fab20e3864c6)

But this scenario occurs randomly, not every time. It seems that the tasks with more complexity, such as computing the multiplication of three large numbers, tend to take longer for ChatGPT to process, leading to this scenario. I will update if it happen again. Thanks

**Comment by PawanOsman** [comment]
@dealdot please try to use unmodified latest version, then if it happened let us know.
