### ISSUE TITLE
axios -> fetch

### ISSUE THREAD

**Issue by QQQQQQQQiu** [PawanOsman/ChatGPT#94]
Hi,could you please create a version that uses fetch? When I use axios, it triggers a Cloudflare validation, but switching to fetch doesn't cause this issue. No idea why though.

**Comment by 283142289** [comment]
const fetchChatGPT = async () => {
    try {
      const response = await fetch('http://127.0.0.1:3040/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: 'gpt-3.5-turbo',
          messages: [{ "role": "user", "content": “ What is LLM ”}],
        }),
      });
  
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }

      const data = await response.json();
      console.log("GPT-3.5 :",data);
      console.log(data.choices[0].message.content);

      return data;
    } catch (error) {
      console.error('There has been a problem with your fetch operation:', error);
    }
  };

**Comment by gamersindo1223** [comment]
@283142289 
```
const fetchChatGPT = async () => {
try {
const response = await fetch('http://127.0.0.1:3040/v1/chat/completions', {
method: 'POST',
headers: {
'Content-Type': 'application/json',
},
body: JSON.stringify({
model: 'gpt-3.5-turbo',
messages: [{ "role": "user", "content": “ What is LLM ”}],
}),
});

  if (!response.ok) {
    throw new Error('Network response was not ok');
  }

  const data = await response.json();
  console.log("GPT-3.5 :",data);
  console.log(data.choices[0].message.content);

  return data;
} catch (error) {
  console.error('There has been a problem with your fetch operation:', error);
}
};
```
