### ISSUE TITLE
Error handling chat completion: AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by jeffery9** [PawanOsman/ChatGPT#97]
chatgpt response with error code` code: 'ERR_BAD_REQUEST' `

axios post data as 

> url: 'https://chat.openai.com/backend-anon/conversation',
> data: '{"action":"next","messages":[{"author":{"role":"user"},"content":{"content_type":"text","parts":["You are also an Odoo expert and have a deep understanding of HTML, sphinx, GetText portable object, reStructuredText, and Markdown specifications. You are skilled at preserving the relevant markups and formatting while translating. Translate the following text to Chinese, Keeping the formatting and markups unchanged, and adding extra spaces around the markups, without providing explanations or expansions: \\n\\n#: ../../content/applications/sales/point_of_sale/pricing/pricelists.rst:81\\nmsgid \\"\\"\\n\\"Define a :doc:`Rounding Method <cash_rounding>` by forcing the price after \\"\\n\\":guilabel:`Discount` to be a multiple of the value set. The :guilabel:`Extra\\"\\n\\" Fee` is applied afterward.\\"\\nmsgstr \\"\\"\\n\\"Define a :doc:`Rounding Method <cash_rounding>` by forcing the price after \\"\\n\\":guilabel:`Discount` to be a multiple of the value set. The :guilabel:`Extra\\"\\n\\" Fee` is applied afterward.\\"\\n\\n "]}}],"parent_message_id":"93c01c77-9f6d-4f55-bda7-ff98a7dcc8b8","model":"text-davinci-002-render-sha","timezone_offset_min":-180,"suggestions":[],"history_and_training_disabled":true,"conversation_mode":{"kind":"primary_assistant"},"websocket_request_id":"9ef4c78b-30e4-44f5-a786-9465d2dfe829"}'

**Comment by jeffery9** [comment]
chatgpt in browser post to api  has set this header `Openai-Sentinel-Proof-Token`, but not does this in the app.js

**Comment by PawanOsman** [comment]
fixed
