### ISSUE TITLE
[Feature Request] support built-in authentication

### ISSUE THREAD

**Issue by love4taylor** [PawanOsman/ChatGPT#98]
Although I can support identity authentication through NGINX, I still need identity authentication in the scenario of using cloudflared to avoid abuse.

**Comment by m00nfly** [comment]
A simple method is to perform authorization verification on the api_key in the client request. Only the authorized api_key can access the reverse proxy API.

I forked this repo and added this function. Setting the API_KEY="xxxxxx" parameter in the .env file, will only allow clients using this api_key to access the API.

You can try my modified version 
[m00nfly/ChatGPT](https://github.com/m00nfly/ChatGPT)
